# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SaturnCli < Formula
  desc "Command-line interface for Saturn Platform"
  homepage "https://github.com/kpizzy812/saturn-cli"
  version "1.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.7.1/saturn-cli_1.7.1_darwin_amd64.tar.gz"
      sha256 "3e85e9de608a76ad713b6ea55cbb41bf5f6bab729dddcd9e95917e3df6a50dd9"

      define_method(:install) do
        bin.install "saturn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.7.1/saturn-cli_1.7.1_darwin_arm64.tar.gz"
      sha256 "868134b69b77f16e79dd29b38358f0a37d6cc37cb0dd10b79dc20c004402e330"

      define_method(:install) do
        bin.install "saturn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.7.1/saturn-cli_1.7.1_linux_amd64.tar.gz"
      sha256 "8b90499024826a2bfdaf2e0994d1bcc8826293662876ffcf8019caf05d436108"
      define_method(:install) do
        bin.install "saturn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.7.1/saturn-cli_1.7.1_linux_arm64.tar.gz"
      sha256 "ce0953ddc6d2266ca112b14aa2d4df4d7fea79fc307ab3886a1520bf8464d21b"
      define_method(:install) do
        bin.install "saturn"
      end
    end
  end

  test do
    assert_match "saturn version", shell_output("#{bin}/saturn version")
  end
end
