# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SaturnCli < Formula
  desc "Command-line interface for Saturn Platform"
  homepage "https://github.com/kpizzy812/saturn-cli"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.6.0/saturn-cli_1.6.0_darwin_amd64.tar.gz"
      sha256 "19e11a4a8eac43cadec948d275ce3bd6f7882f8607bbb51f6b1c31787a960d15"

      define_method(:install) do
        bin.install "saturn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.6.0/saturn-cli_1.6.0_darwin_arm64.tar.gz"
      sha256 "833b3d14411e9d8c329f03e13f261fda0bd0e0d258c669cbd34a19b8854bfb07"

      define_method(:install) do
        bin.install "saturn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.6.0/saturn-cli_1.6.0_linux_amd64.tar.gz"
      sha256 "49f47f2257e0b2f3ef20c6bed75b67d1f04dde16899bde29c1c39ecb06c9222a"
      define_method(:install) do
        bin.install "saturn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kpizzy812/saturn-cli/releases/download/v1.6.0/saturn-cli_1.6.0_linux_arm64.tar.gz"
      sha256 "d2d0136c50f0d7a196e498ac439de7c5e50b8f18eab96ab18c0023b1052515c9"
      define_method(:install) do
        bin.install "saturn"
      end
    end
  end

  test do
    assert_match "saturn version", shell_output("#{bin}/saturn version")
  end
end
